# Starter pipeline
trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
  - job: A1
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'd4cb9f73-8cc5-477d-8c52-564663d622e4'
        definition: '2'
        buildVersionToDownload: 'latest'
        targetPath: '$(Pipeline.Workspace)'
    - task: AzureRmWebAppDeployment@5
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(e312dbab-2dd8-4a17-bb74-6a928e44c4a9)'
        appType: 'webAppLinux'
        WebAppName: 'abookstore'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        DeploymentTypeLinux: 'oneDeploy'