# Starter pipeline
trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadBuildArtifacts@1
  inputs:
    buildType: 'specific'
    project: 'd4cb9f73-8cc5-477d-8c52-564663d622e4'
    pipeline: '1'
    buildVersionToDownload: 'latest'
    downloadType: 'specific'
    downloadPath: '$(System.ArtifactsDirectory)'

- task: AzureRmWebAppDeployment@5
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(e312dbab-2dd8-4a17-bb74-6a928e44c4a9)'
    appType: 'webApp'
    WebAppName: 'aBookStore'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
